name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install dependencies
      run: sudo apt update && sudo apt install libreadline-dev:i386 libc6-dev-i386 gcc-multilib
      
    - name: Build libsamwid.so
      working-directory: lib
      run: make
